# Options:
# Vanilla - Vanilla Block Setting (slow, not recommended)
# FAWE - Hooks into FastAsyncWorldEdit. Requires the plugin to be installed
# AWE - Hooks into AsyncWorldEdit. Requires the plugin to be installed
# WE - Hooks into WorldEdit. Requires the plugin to be installed
# Auto - Hooks into the fastest plugin it can find, or uses Vanilla if no plugins are installed
BlockSettingMethod: Auto

DefaultLanguage: "en"
